spring:
  application:
    name: product-service

server:
  port: 8090

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/microservices_product
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

order:
  service:
    url: http://order-service:8085

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka

---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_product
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
order:
  service:
    url: http://localhost:8085

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka