spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://postgres:5432/microservices_product
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8090

order:
  service:
    url: http://localhost:8085

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka